# This is a Docker Compose file that defines the services and their configurations for a multi-container application.

version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: enersense
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d" ,"enersense", "-U", "postgres_user"]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - app-network

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    command: mosquitto -p 1883
    networks:
      - app-network
    
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      postgres-db:
        condition: service_healthy
    ports: [ "${API_PORT:-8000}:8000" ]
    command:
      - uvicorn
      - app.rest_api:APP
      - --host
      - "0"
      - --port
      - "8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge